[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.733.2"
deca-VampireCommandFramework = "0.10.2"

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"

[publish.categories]
v-rising = ["oakveil-update", "mods", "server"]

[package]
namespace = "zfolmt"
name = "Penumbra"
versionNumber = "1.1.5"
description = "Simple custom merchants, use defaults or create your own!"
websiteUrl = "https://github.com/mfoltz/Penumbra"
containsNsfwContent = false
